package ru.uchetka.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.database.sqlite.*;import android.database.Cursor;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.security.MessageDigest;import java.text.SimpleDateFormat;import java.util.*;import android.net.Uri;

public class MainActivity extends Activity {
  DB db; LinearLayout root,content; final int GREEN=Color.rgb(73,100,74), DARK=Color.rgb(23,26,23), PAPER=Color.rgb(243,241,233), ACC=Color.rgb(169,139,82); android.content.SharedPreferences sp;
  TextView title; int pad=18;
  public void onCreate(Bundle b){super.onCreate(b); db=new DB(this); sp=getSharedPreferences("auth",0); if(!sp.contains("pass")) setupPassword(); else login();}
  TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(DARK);t.setPadding(pad,pad,pad,pad);return t;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setOnClickListener(v->{});return b;}
  void base(String ttl){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(PAPER); title=tv(ttl,22);title.setTextColor(Color.WHITE);title.setBackgroundColor(DARK);root.addView(title,new LinearLayout.LayoutParams(-1,70));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(12,10,12,20);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
  void setupPassword(){base("УЧЕТКА • Первый запуск"); content.addView(tv("Создайте локальный пароль. Учетная запись и интернет не требуются.",18)); EditText a=new EditText(this);a.setHint("Новый пароль");a.setInputType(129);content.addView(a);EditText c=new EditText(this);c.setHint("Повторите пароль");c.setInputType(129);content.addView(c);Button b=btn("Сохранить пароль");content.addView(b);b.setOnClickListener(v->{if(a.getText().length()<4||!a.getText().toString().equals(c.getText().toString())){toast("Пароли должны совпадать и содержать минимум 4 символа");return;}sp.edit().putString("pass",hash(a.getText().toString())).apply();dashboard();});}
  void login(){base("УЧЕТКА • Вход");content.addView(tv("Введите локальный пароль",18));EditText p=new EditText(this);p.setHint("Пароль");p.setInputType(129);content.addView(p);Button b=btn("Войти");content.addView(b);b.setOnClickListener(v->{if(hash(p.getText().toString()).equals(sp.getString("pass","")))dashboard();else toast("Неверный пароль");});}
  void dashboard(){base("УЧЕТКА");content.addView(tv("Учет служебного времени",20));Button people=btn("👥 Личный состав");Button add=btn("⏱ Добавить время");Button journal=btn("📋 Журнал");Button report=btn("📊 Сводка");Button settings=btn("⚙ Настройки");for(Button x:new Button[]{people,add,journal,report,settings})content.addView(x);people.setOnClickListener(v->people());add.setOnClickListener(v->event());journal.setOnClickListener(v->journal());report.setOnClickListener(v->report());settings.setOnClickListener(v->settings());}
  void people(){base("ЛИЧНЫЙ СОСТАВ");Button n=btn("+ Добавить военнослужащего");content.addView(n);n.setOnClickListener(v->addPerson());Cursor c=db.raw("SELECT id,name,rank,position FROM people ORDER BY name",null);while(c.moveToNext()){long id=c.getLong(0);TextView t=tv(c.getString(1)+"\n"+c.getString(2)+" • "+c.getString(3),17);t.setBackgroundColor(Color.WHITE);content.addView(t);Button del=btn("Удалить");content.addView(del);del.setOnClickListener(v->{db.exec("DELETE FROM people WHERE id=?",new String[]{""+id});people();});}c.close();Button back=btn("← Назад");content.addView(back);back.setOnClickListener(v->dashboard());}
  void addPerson(){base("НОВЫЙ ВОЕННОСЛУЖАЩИЙ");EditText name=field("Фамилия И.О.");EditText rank=field("Звание");EditText pos=field("Должность");content.addView(name);content.addView(rank);content.addView(pos);Button save=btn("Сохранить");content.addView(save);save.setOnClickListener(v->{if(name.getText().length()==0){toast("Укажите Фамилию И.О.");return;}db.exec("INSERT INTO people(name,rank,position) VALUES(?,?,?)",new String[]{name.getText().toString(),rank.getText().toString(),pos.getText().toString()});people();});}
  EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);return e;}
  void event(){base("ДОБАВИТЬ ВРЕМЯ");Spinner who=new Spinner(this);ArrayList<String> labels=new ArrayList<>();ArrayList<Long> ids=new ArrayList<>();Cursor c=db.raw("SELECT id,name FROM people ORDER BY name",null);while(c.moveToNext()){ids.add(c.getLong(0));labels.add(c.getString(1));}c.close();who.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));content.addView(tv("Военнослужащий",15));content.addView(who);EditText date=field("Дата YYYY-MM-DD");date.setText(new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));content.addView(date);EditText hours=field("Количество часов (например 2.5)");hours.setInputType(2|8192);content.addView(hours);EditText type=field("Вид: рабочий день / выходной / праздник");content.addView(type);EditText basis=field("Основание / примечание");content.addView(basis);Button save=btn("Записать");content.addView(save);save.setOnClickListener(v->{try{if(ids.size()==0){toast("Сначала добавьте личный состав");return;}double h=Double.parseDouble(hours.getText().toString().replace(',','.'));db.exec("INSERT INTO events(person_id,date,hours,type,basis) VALUES(?,?,?,?,?)",new String[]{""+ids.get(who.getSelectedItemPosition()),date.getText().toString(),""+h,type.getText().toString(),basis.getText().toString()});toast("Записано");dashboard();}catch(Exception e){toast("Проверьте дату и количество часов");}});}
  void journal(){base("ЖУРНАЛ");Cursor c=db.raw("SELECT e.date,p.name,e.hours,e.type,e.basis FROM events e JOIN people p ON p.id=e.person_id ORDER BY e.date DESC,e.id DESC",null);while(c.moveToNext())content.addView(tv(c.getString(0)+" • "+c.getString(1)+"\n"+fmt(c.getDouble(2))+" ч • "+c.getString(3)+"\n"+c.getString(4),16));c.close();Button back=btn("← Назад");content.addView(back);back.setOnClickListener(v->dashboard());}
  void report(){base("СВОДКА");Cursor c=db.raw("SELECT p.name,COALESCE(SUM(e.hours),0) FROM people p LEFT JOIN events e ON p.id=e.person_id GROUP BY p.id ORDER BY p.name",null);while(c.moveToNext())content.addView(tv(c.getString(0)+" — "+fmt(c.getDouble(1))+" ч",17));c.close();Button csv=btn("Экспорт CSV");content.addView(csv);csv.setOnClickListener(v->exportCsv());Button back=btn("← Назад");content.addView(back);back.setOnClickListener(v->dashboard());}
  void exportCsv(){StringBuilder s=new StringBuilder("Дата;Военнослужащий;Часы;Вид;Основание\n");Cursor c=db.raw("SELECT e.date,p.name,e.hours,e.type,e.basis FROM events e JOIN people p ON p.id=e.person_id ORDER BY e.date",null);while(c.moveToNext())s.append(c.getString(0)).append(';').append(c.getString(1)).append(';').append(c.getDouble(2)).append(';').append(c.getString(3)).append(';').append(c.getString(4)).append('\n');c.close();Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/csv");i.putExtra(Intent.EXTRA_TEXT,s.toString());startActivity(Intent.createChooser(i,"Передать CSV"));}
  void settings(){base("НАСТРОЙКИ");content.addView(tv("Локальное хранение включено. Приложение не требует учетной записи и не отправляет данные на сервер.\n\nНе используйте приложение для сведений, составляющих государственную тайну или иных данных с ограниченным режимом обработки.",16));Button ch=btn("Сменить пароль");content.addView(ch);ch.setOnClickListener(v->changePassword());Button out=btn("Выйти");content.addView(out);out.setOnClickListener(v->login());Button back=btn("← Назад");content.addView(back);back.setOnClickListener(v->dashboard());}
  void changePassword(){base("СМЕНА ПАРОЛЯ");EditText a=field("Текущий пароль");a.setInputType(129);EditText b=field("Новый пароль");b.setInputType(129);EditText c=field("Повтор нового пароля");c.setInputType(129);content.addView(a);content.addView(b);content.addView(c);Button save=btn("Изменить");content.addView(save);save.setOnClickListener(v->{if(!hash(a.getText().toString()).equals(sp.getString("pass",""))){toast("Текущий пароль неверен");return;}if(b.length()<4||!b.getText().toString().equals(c.getText().toString())){toast("Проверьте новый пароль");return;}sp.edit().putString("pass",hash(b.getText().toString())).apply();toast("Пароль изменен");settings();});}
  String fmt(double d){return String.format(Locale.US,"%.2f",d).replace(".00","").replace('.',',');}
  String hash(String s){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes("UTF-8"));StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format("%02x",q));return x.toString();}catch(Exception e){return "";}}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
  static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"uchetka.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE people(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,rank TEXT,position TEXT)");d.execSQL("CREATE TABLE events(id INTEGER PRIMARY KEY AUTOINCREMENT,person_id INTEGER,date TEXT,hours REAL,type TEXT,basis TEXT)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}Cursor raw(String q,String[] a){return getReadableDatabase().rawQuery(q,a);}void exec(String q,String[] a){getWritableDatabase().execSQL(q,a);}}
}
